apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-rwx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn